# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
module "vpc_lite" {
  source = "../../../modules/vpc-lite"

  project = var.project
  env     = var.env

  name    = var.name
  cidr    = var.cidr
  azs     = var.azs
  subnets = var.subnets
}

output "vpc_id" { value = module.vpc_lite.vpc_id }
output "public_subnet_ids" { value = module.vpc_lite.public_subnet_ids }
