# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_version = ">= 1.6"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

variable "aws_region" { type = string }
variable "aws_profile" { type = string }

provider "aws" {
  region  = var.aws_region
  profile = var.aws_profile
}
