# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
module "ec2_lite" {
  source = "../../../modules/ec2-lite"

  project = var.project
  env     = var.env
  name    = var.name

  vpc_id    = "vpc-0af04ef37c301b9c0"
  subnet_id = "subnet-0e5b4dba32d93493c"

  instance_type = var.instance_type
  key_name      = var.key_name
  ssh_cidr      = var.ssh_cidr
}

output "instance_id" { value = module.ec2_lite.instance_id }
output "public_ip" { value = module.ec2_lite.public_ip }
output "sg_id" { value = module.ec2_lite.sg_id }
