# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
variable "project" { type = string }
variable "env" { type = string }
variable "name" { type = string }
variable "instance_type" { type = string }
variable "key_name" { type = string }
variable "ssh_cidr" { type = string }
