name: Mirror to GitLab

on:
  push:
    branches: ["**"]
    tags: ["*"]
  delete:
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git identity
        run: |
          git config user.name  "${{ secrets.GIT_AUTHOR_NAME || 'ci-bot' }}"
          git config user.email "${{ secrets.GIT_AUTHOR_EMAIL || 'ci-bot@users.noreply.github.com' }}"

      - name: Push branches & tags to GitLab (safe, all branches)
        env:
          GITLAB_URL: ${{ secrets.GITLAB_URL }}
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          set -euo pipefail

          GITLAB_REMOTE="https://oauth2:${GITLAB_TOKEN}@${GITLAB_URL#https://}"
          git remote add gitlab "$GITLAB_REMOTE" || git remote set-url gitlab "$GITLAB_REMOTE"

          git fetch --prune --tags origin '+refs/heads/*:refs/remotes/origin/*'

          git push --prune gitlab 'refs/remotes/origin/*:refs/heads/*'

          git push gitlab --tags
